# Generated by Django 4.1 on 2022-10-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_material_purpose_person_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='materials',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
